## Generated by rosdoc2.verbs.build.builders.SphinxBuilder.

# Configuration file for the Sphinx documentation builder.

# rosdoc2 runs sphinx in a wrapping directory so that output does not contaminate
# the source repository. The wrapping directory includes a 'wrapping' conf.py file
# which imports this file or a user-provided version, and extends it to support
# Breathe and Exhale.
#
# This default file is used if the user does not provide their own conf.py file.
# The minimal content of this file, as you can see below, is nothing, as standard
# defaults which work with ros documentation generation are provided in the
# wrapping conf.py file. We recommend that, if you provide your own conf.py file,
# that you only include settings that you want to change from the defaults.
#
# If you want to see what the defaults are, you can run rosdoc2 on a package, and
# look at the generated conf.py file in the build folder under the package's
# documentation build folder.
