# Goal
string BOUSTROPHEDON=BousPlanner
string SPANNINGTREE=SpanningTreePlanner
string SKELETON=SkeletonPlanner

string planner_type
bool verbose

---
# Result
bool success
string message

---
# Feedback
float32 completion_percentage
float32 distance_remaining
int32 current_segment
int32 total_segments