'''
    Navigator types
'''

import numpy as np
import cv2
import fields2cover as f2c
from geometry_msgs.msg import PolygonStamped, Point32
from visualization_msgs.msg import Marker, MarkerArray
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped

class SystematicNavigator():
    def __init__(self, node, resolution=0.1, map_resolution=0.05, lethal_threshold=50.0):
        '''
        Systematic navigator class
        '''
        self.navigator_type = 'systematic'
        self.path = None
        self.map = None
        self.threshold = lethal_threshold
        self.resolution = resolution
        self.map_resolution = map_resolution
        self.node = node
        
        self.polymap_publisher = self.node.create_publisher(
            PolygonStamped, f'/{self.name}/map_contours', 10)

        self.decomp_publisher = self.node.create_publisher(
            MarkerArray, f'/{self.name}/decomposed_map', 10)
   
    def update_map(self, new_map):
        """update internal map of the navigator

        Args:
            new_map (Array like): new map to update the navigator with

        Returns:
            path: path generated by update_map
        """        '''
        '''
        self.map = new_map

        # Convert costmap to binary grid
        self.binary_costmap = np.zeros_like(self.map)
        self.binary_costmap = self.binary_costmap.astype(np.uint8)
        free_mask = np.zeros_like(self.map, dtype=np.uint8)
        free_mask[self.map < self.threshold] = 255

        contours, _ = cv2.findContours(free_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        if not contours:
            return None

        largest = max(contours, key=cv2.contourArea)
        self.publish_polygon(largest)
        points = []
        for p in largest.squeeze():
            px, py = p
            x = px * self.map_resolution
            y = py * self.map_resolution
            points.append(f2c.Point(x, y))

        points.append(points[0])

        ring = f2c.LinearRing()
        for p in points:
            ring.addPoint(p)

        cell = f2c.Cell(ring)
        self.field = f2c.Field([cell])
        
        self.generate_path()
        return self.path
    
    def visualize(self, poly_map=True, decomp_map=True, path=True):
        f2c.Visualizer.figure()
        f2c.Visualizer.plot(self.field)
        
    def publish_polygon(self, contour):
        msg = PolygonStamped()
        msg.header.frame_id = "map"
        msg.header.stamp = self.node.get_clock().now().to_msg()

        for p in contour.squeeze():
            px, py = p
            point = Point32()
            point.x = px * self.map_resolution
            point.y = py * self.map_resolution
            point.z = 0.0
            msg.polygon.points.append(point)

        self.polymap_publisher.publish(msg)
    
    def publish_decomposition(self):
        marker_array = MarkerArray()

        for i, cell in enumerate(self.cells):
            marker = Marker()
            marker.header.frame_id = "map"
            marker.header.stamp = self.node.get_clock().now().to_msg()

            marker.ns = "decomposition"
            marker.id = i
            marker.type = Marker.LINE_STRIP
            marker.action = Marker.ADD

            marker.scale.x = 0.02

            marker.color.r = (i % 3 == 0)
            marker.color.g = (i % 3 == 1)
            marker.color.b = (i % 3 == 2)
            marker.color.a = 1.0

            ring = cell.getGeometry().getOuterRing()

            for j in range(ring.size()):
                p = ring.getPoint(j)

                pt = PoseStamped().pose.position
                pt.x = p.getX()
                pt.y = p.getY()
                pt.z = 0.0

                marker.points.append(pt)

            # close the loop
            if ring.size() > 0:
                first = ring.getPoint(0)
                pt = PoseStamped().pose.position
                pt.x = first.getX()
                pt.y = first.getY()
                pt.z = 0.0
                marker.points.append(pt)

            marker_array.markers.append(marker)

        self.decomp_publisher.publish(marker_array)
    
    def publish_info(self, poly_map=True, decomp_map=True, path=True):
        if poly_map:
            self.polymap_publisher.publish()
        
        if decomp_map:
            self.decomp_publisher.publish()
        
        if path:
            self.path_publisher.publish()

    def generate_path(self):
        pass

class ReactiveNavigator():
    def __init__(self):
        self.navigator_type = 'reactive'